name: pages-deploy
permissions:
  contents: write
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'website/'
      - '.github/workflows/pages-deploy.yml'
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.2
      with:
        cache: yarn
    - name: Build project
      run: |
        cd website
        yarn
        yarn build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./website/build
