name: pages-deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'website/'
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - run: cd website
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.2      
    - name: Install dependencies
      run: yarn
    - name: Build project
      run: yarn build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build
